"""initial tables

Revision ID: a75e7af30698
Revises: 
Create Date: 2026-08-26 10:44:21.220715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75e7af30698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_behaviors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_behaviors_id'), 'user_behaviors', ['id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_product_id'), 'user_behaviors', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_user_id'), 'user_behaviors', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_behaviors_user_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_product_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_id'), table_name='user_behaviors')
    op.drop_table('user_behaviors')
    # ### end Alembic commands ###