apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include("ecommerce-service.fullname", .) }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce-service.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "INFO"
  JAVA_OPTS: "-Xmx512m -XX:+UseG1GC"
  PYTHON_LOG_LEVEL: "INFO"
