apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ecommerce-service.labels" . | nindent 4 }}
