apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
  labels:
    app: ecommerce
data:
  DATABASE_HOST: "postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ecommerce"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "msk-broker:9092"
  KONG_HOST: "kong-proxy.kong.svc.cluster.local"
  KONG_PORT: "8000"
