apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ecommerce-base
  namespace: ecommerce
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - postgres-redis.yaml
