apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
