apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: cGFzc3dvcmQ=
  REDIS_PASSWORD: ""
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtbWU=
  STRIPE_API_KEY: c3RyaXBlLWFwaS1rZXk=
