"""initial tables

Revision ID: 97c0c0703ae0
Revises: 
Create Date: 2026-08-26 10:43:02.084228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c0c0703ae0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('average_order_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_analytics_date'), 'sales_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_sales_analytics_id'), 'sales_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_analytics_id'), table_name='sales_analytics')
    op.drop_index(op.f('ix_sales_analytics_date'), table_name='sales_analytics')
    op.drop_table('sales_analytics')
    # ### end Alembic commands ###